// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/relaypb/relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayMessageFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Version  uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	StreamId string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Ack      uint32                 `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	AckBits  uint32                 `protobuf:"varint,4,opt,name=ack_bits,json=ackBits,proto3" json:"ack_bits,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RelayMessageFrame_Data
	//	*RelayMessageFrame_AckFrame
	//	*RelayMessageFrame_Resume
	//	*RelayMessageFrame_Reset_
	//	*RelayMessageFrame_Heartbeat
	//	*RelayMessageFrame_Handshake
	Body          isRelayMessageFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessageFrame) Reset() {
	*x = RelayMessageFrame{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessageFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessageFrame) ProtoMessage() {}

func (x *RelayMessageFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessageFrame.ProtoReflect.Descriptor instead.
func (*RelayMessageFrame) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayMessageFrame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RelayMessageFrame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *RelayMessageFrame) GetAck() uint32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *RelayMessageFrame) GetAckBits() uint32 {
	if x != nil {
		return x.AckBits
	}
	return 0
}

func (x *RelayMessageFrame) GetBody() isRelayMessageFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RelayMessageFrame) GetData() *RelayData {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *RelayMessageFrame) GetAckFrame() *RelayAck {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_AckFrame); ok {
			return x.AckFrame
		}
	}
	return nil
}

func (x *RelayMessageFrame) GetResume() *RelayResume {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *RelayMessageFrame) GetReset_() *RelayReset {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *RelayMessageFrame) GetHeartbeat() *RelayHeartbeat {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RelayMessageFrame) GetHandshake() *RelayHandshake {
	if x != nil {
		if x, ok := x.Body.(*RelayMessageFrame_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

type isRelayMessageFrame_Body interface {
	isRelayMessageFrame_Body()
}

type RelayMessageFrame_Data struct {
	Data *RelayData `protobuf:"bytes,5,opt,name=data,proto3,oneof"`
}

type RelayMessageFrame_AckFrame struct {
	AckFrame *RelayAck `protobuf:"bytes,6,opt,name=ack_frame,json=ackFrame,proto3,oneof"`
}

type RelayMessageFrame_Resume struct {
	Resume *RelayResume `protobuf:"bytes,7,opt,name=resume,proto3,oneof"`
}

type RelayMessageFrame_Reset_ struct {
	Reset_ *RelayReset `protobuf:"bytes,8,opt,name=reset,proto3,oneof"`
}

type RelayMessageFrame_Heartbeat struct {
	Heartbeat *RelayHeartbeat `protobuf:"bytes,9,opt,name=heartbeat,proto3,oneof"`
}

type RelayMessageFrame_Handshake struct {
	Handshake *RelayHandshake `protobuf:"bytes,10,opt,name=handshake,proto3,oneof"`
}

func (*RelayMessageFrame_Data) isRelayMessageFrame_Body() {}

func (*RelayMessageFrame_AckFrame) isRelayMessageFrame_Body() {}

func (*RelayMessageFrame_Resume) isRelayMessageFrame_Body() {}

func (*RelayMessageFrame_Reset_) isRelayMessageFrame_Body() {}

func (*RelayMessageFrame_Heartbeat) isRelayMessageFrame_Body() {}

func (*RelayMessageFrame_Handshake) isRelayMessageFrame_Body() {}

type RelayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	SegmentIndex  uint32                 `protobuf:"varint,2,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	SegmentCount  uint32                 `protobuf:"varint,3,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayData) Reset() {
	*x = RelayData{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayData) ProtoMessage() {}

func (x *RelayData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayData.ProtoReflect.Descriptor instead.
func (*RelayData) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayData) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RelayData) GetSegmentIndex() uint32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *RelayData) GetSegmentCount() uint32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *RelayData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RelayAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAck) Reset() {
	*x = RelayAck{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAck) ProtoMessage() {}

func (x *RelayAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAck.ProtoReflect.Descriptor instead.
func (*RelayAck) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{2}
}

type RelayResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSeq       uint32                 `protobuf:"varint,1,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResume) Reset() {
	*x = RelayResume{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResume) ProtoMessage() {}

func (x *RelayResume) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResume.ProtoReflect.Descriptor instead.
func (*RelayResume) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RelayResume) GetNextSeq() uint32 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type RelayReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayReset) Reset() {
	*x = RelayReset{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayReset) ProtoMessage() {}

func (x *RelayReset) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayReset.ProtoReflect.Descriptor instead.
func (*RelayReset) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RelayReset) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RelayHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayHeartbeat) Reset() {
	*x = RelayHeartbeat{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayHeartbeat) ProtoMessage() {}

func (x *RelayHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayHeartbeat.ProtoReflect.Descriptor instead.
func (*RelayHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{5}
}

type RelayHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayHandshake) Reset() {
	*x = RelayHandshake{}
	mi := &file_internal_relaypb_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayHandshake) ProtoMessage() {}

func (x *RelayHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relaypb_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayHandshake.ProtoReflect.Descriptor instead.
func (*RelayHandshake) Descriptor() ([]byte, []int) {
	return file_internal_relaypb_relay_proto_rawDescGZIP(), []int{6}
}

func (x *RelayHandshake) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_relaypb_relay_proto protoreflect.FileDescriptor

const file_internal_relaypb_relay_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/relaypb/relay.proto\x12\x1acodex.exec_server.relay.v1\"\x9c\x04\n" +
	"\x11RelayMessageFrame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\rR\x03ack\x12\x19\n" +
	"\back_bits\x18\x04 \x01(\rR\aackBits\x12;\n" +
	"\x04data\x18\x05 \x01(\v2%.codex.exec_server.relay.v1.RelayDataH\x00R\x04data\x12C\n" +
	"\tack_frame\x18\x06 \x01(\v2$.codex.exec_server.relay.v1.RelayAckH\x00R\backFrame\x12A\n" +
	"\x06resume\x18\a \x01(\v2'.codex.exec_server.relay.v1.RelayResumeH\x00R\x06resume\x12>\n" +
	"\x05reset\x18\b \x01(\v2&.codex.exec_server.relay.v1.RelayResetH\x00R\x05reset\x12J\n" +
	"\theartbeat\x18\t \x01(\v2*.codex.exec_server.relay.v1.RelayHeartbeatH\x00R\theartbeat\x12J\n" +
	"\thandshake\x18\n" +
	" \x01(\v2*.codex.exec_server.relay.v1.RelayHandshakeH\x00R\thandshakeB\x06\n" +
	"\x04body\"\x81\x01\n" +
	"\tRelayData\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12#\n" +
	"\rsegment_index\x18\x02 \x01(\rR\fsegmentIndex\x12#\n" +
	"\rsegment_count\x18\x03 \x01(\rR\fsegmentCount\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\n" +
	"\n" +
	"\bRelayAck\"(\n" +
	"\vRelayResume\x12\x19\n" +
	"\bnext_seq\x18\x01 \x01(\rR\anextSeq\"$\n" +
	"\n" +
	"RelayReset\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x10\n" +
	"\x0eRelayHeartbeat\"*\n" +
	"\x0eRelayHandshake\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayloadB=Z;github.com/agentserver/agentserver/internal/relaypb;relaypbb\x06proto3"

var (
	file_internal_relaypb_relay_proto_rawDescOnce sync.Once
	file_internal_relaypb_relay_proto_rawDescData []byte
)

func file_internal_relaypb_relay_proto_rawDescGZIP() []byte {
	file_internal_relaypb_relay_proto_rawDescOnce.Do(func() {
		file_internal_relaypb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_relaypb_relay_proto_rawDesc), len(file_internal_relaypb_relay_proto_rawDesc)))
	})
	return file_internal_relaypb_relay_proto_rawDescData
}

var file_internal_relaypb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_relaypb_relay_proto_goTypes = []any{
	(*RelayMessageFrame)(nil), // 0: codex.exec_server.relay.v1.RelayMessageFrame
	(*RelayData)(nil),         // 1: codex.exec_server.relay.v1.RelayData
	(*RelayAck)(nil),          // 2: codex.exec_server.relay.v1.RelayAck
	(*RelayResume)(nil),       // 3: codex.exec_server.relay.v1.RelayResume
	(*RelayReset)(nil),        // 4: codex.exec_server.relay.v1.RelayReset
	(*RelayHeartbeat)(nil),    // 5: codex.exec_server.relay.v1.RelayHeartbeat
	(*RelayHandshake)(nil),    // 6: codex.exec_server.relay.v1.RelayHandshake
}
var file_internal_relaypb_relay_proto_depIdxs = []int32{
	1, // 0: codex.exec_server.relay.v1.RelayMessageFrame.data:type_name -> codex.exec_server.relay.v1.RelayData
	2, // 1: codex.exec_server.relay.v1.RelayMessageFrame.ack_frame:type_name -> codex.exec_server.relay.v1.RelayAck
	3, // 2: codex.exec_server.relay.v1.RelayMessageFrame.resume:type_name -> codex.exec_server.relay.v1.RelayResume
	4, // 3: codex.exec_server.relay.v1.RelayMessageFrame.reset:type_name -> codex.exec_server.relay.v1.RelayReset
	5, // 4: codex.exec_server.relay.v1.RelayMessageFrame.heartbeat:type_name -> codex.exec_server.relay.v1.RelayHeartbeat
	6, // 5: codex.exec_server.relay.v1.RelayMessageFrame.handshake:type_name -> codex.exec_server.relay.v1.RelayHandshake
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_relaypb_relay_proto_init() }
func file_internal_relaypb_relay_proto_init() {
	if File_internal_relaypb_relay_proto != nil {
		return
	}
	file_internal_relaypb_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*RelayMessageFrame_Data)(nil),
		(*RelayMessageFrame_AckFrame)(nil),
		(*RelayMessageFrame_Resume)(nil),
		(*RelayMessageFrame_Reset_)(nil),
		(*RelayMessageFrame_Heartbeat)(nil),
		(*RelayMessageFrame_Handshake)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_relaypb_relay_proto_rawDesc), len(file_internal_relaypb_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_relaypb_relay_proto_goTypes,
		DependencyIndexes: file_internal_relaypb_relay_proto_depIdxs,
		MessageInfos:      file_internal_relaypb_relay_proto_msgTypes,
	}.Build()
	File_internal_relaypb_relay_proto = out.File
	file_internal_relaypb_relay_proto_goTypes = nil
	file_internal_relaypb_relay_proto_depIdxs = nil
}
