package devstack

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

var environmentNamePattern = regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`)

func renderEnvironmentFile(environment map[string]string) ([]byte, error) {
	if len(environment) == 0 {
		return nil, errors.New("development service environment cannot be empty")
	}
	names := make([]string, 0, len(environment))
	for name, value := range environment {
		if !environmentNamePattern.MatchString(name) {
			return nil, fmt.Errorf("invalid development environment name %q", name)
		}
		if err := validateShellValue("environment "+name, value); err != nil {
			return nil, err
		}
		names = append(names, name)
	}
	sort.Strings(names)
	var output bytes.Buffer
	output.WriteString("# Generated by agentserver-dev prepare --insecure-dev. Do not commit.\n")
	for _, name := range names {
		output.WriteString("export ")
		output.WriteString(name)
		output.WriteString("=")
		output.WriteString(quoteShellSingle(environment[name]))
		output.WriteString("\n")
	}
	return output.Bytes(), nil
}

func quoteShellSingle(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

// ReadEnvironmentFile parses the strict shell-compatible format emitted by
// Prepare. It exists for launch tooling and contract tests; it does not parse
// arbitrary shell or dotenv syntax.
func ReadEnvironmentFile(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseEnvironment(raw)
}

func ParseEnvironment(raw []byte) (map[string]string, error) {
	if len(raw) == 0 || len(raw) > 1024*1024 {
		return nil, errors.New("generated environment file has an invalid size")
	}
	result := make(map[string]string)
	scanner := bufio.NewScanner(bytes.NewReader(raw))
	scanner.Buffer(make([]byte, 4096), 1024*1024)
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line, ok := strings.CutPrefix(line, "export ")
		if !ok {
			return nil, fmt.Errorf("environment line %d is not an export assignment", lineNumber)
		}
		name, encoded, ok := strings.Cut(line, "=")
		if !ok || !environmentNamePattern.MatchString(name) {
			return nil, fmt.Errorf("environment line %d has invalid assignment framing", lineNumber)
		}
		if _, duplicate := result[name]; duplicate {
			return nil, fmt.Errorf("environment line %d repeats %s", lineNumber, name)
		}
		value, err := parseShellSingleQuoted(encoded)
		if err != nil {
			return nil, fmt.Errorf("environment line %d: %w", lineNumber, err)
		}
		result[name] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(result) == 0 {
		return nil, errors.New("generated environment file contains no assignments")
	}
	return result, nil
}

func parseShellSingleQuoted(value string) (string, error) {
	if len(value) < 2 || value[0] != '\'' {
		return "", errors.New("environment value is not single quoted")
	}
	var decoded strings.Builder
	for index := 0; index < len(value); {
		if value[index] != '\'' {
			return "", errors.New("environment value has invalid single-quote framing")
		}
		index++
		closing := strings.IndexByte(value[index:], '\'')
		if closing < 0 {
			return "", errors.New("environment value has an unterminated single-quoted segment")
		}
		closing += index
		decoded.WriteString(value[index:closing])
		index = closing + 1
		if index == len(value) {
			return decoded.String(), nil
		}
		if !strings.HasPrefix(value[index:], `"'"`) {
			return "", errors.New("environment value contains unsupported shell syntax")
		}
		decoded.WriteByte('\'')
		index += len(`"'"`)
	}
	return "", errors.New("environment value has invalid framing")
}
