// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/server/exec_audit_pb/audit.proto

package execauditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BatchRecords is the body of POST /internal/exec-audit/batch.
type BatchRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Records       []*WALRecord           `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRecords) Reset() {
	*x = BatchRecords{}
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecords) ProtoMessage() {}

func (x *BatchRecords) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecords.ProtoReflect.Descriptor instead.
func (*BatchRecords) Descriptor() ([]byte, []int) {
	return file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRecords) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *BatchRecords) GetRecords() []*WALRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// WALRecord is one entry in either the gateway's on-disk WAL or the
// batched upload body. Exactly one body field is set.
//
// Field tag 5 is reserved (was CallEnd before request-only audit).
type WALRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID of the underlying audit row (session or call)
	// Types that are valid to be assigned to Body:
	//
	//	*WALRecord_SessionOpen
	//	*WALRecord_SessionClose
	//	*WALRecord_CallStart
	Body          isWALRecord_Body       `protobuf_oneof:"body"`
	WrittenAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALRecord) Reset() {
	*x = WALRecord{}
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRecord) ProtoMessage() {}

func (x *WALRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRecord.ProtoReflect.Descriptor instead.
func (*WALRecord) Descriptor() ([]byte, []int) {
	return file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP(), []int{1}
}

func (x *WALRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WALRecord) GetBody() isWALRecord_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WALRecord) GetSessionOpen() *SessionOpen {
	if x != nil {
		if x, ok := x.Body.(*WALRecord_SessionOpen); ok {
			return x.SessionOpen
		}
	}
	return nil
}

func (x *WALRecord) GetSessionClose() *SessionClose {
	if x != nil {
		if x, ok := x.Body.(*WALRecord_SessionClose); ok {
			return x.SessionClose
		}
	}
	return nil
}

func (x *WALRecord) GetCallStart() *CallStart {
	if x != nil {
		if x, ok := x.Body.(*WALRecord_CallStart); ok {
			return x.CallStart
		}
	}
	return nil
}

func (x *WALRecord) GetWrittenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

type isWALRecord_Body interface {
	isWALRecord_Body()
}

type WALRecord_SessionOpen struct {
	SessionOpen *SessionOpen `protobuf:"bytes,2,opt,name=session_open,json=sessionOpen,proto3,oneof"`
}

type WALRecord_SessionClose struct {
	SessionClose *SessionClose `protobuf:"bytes,3,opt,name=session_close,json=sessionClose,proto3,oneof"`
}

type WALRecord_CallStart struct {
	CallStart *CallStart `protobuf:"bytes,4,opt,name=call_start,json=callStart,proto3,oneof"`
}

func (*WALRecord_SessionOpen) isWALRecord_Body() {}

func (*WALRecord_SessionClose) isWALRecord_Body() {}

func (*WALRecord_CallStart) isWALRecord_Body() {}

type SessionOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExeId         string                 `protobuf:"bytes,3,opt,name=exe_id,json=exeId,proto3" json:"exe_id,omitempty"`
	TurnId        string                 `protobuf:"bytes,4,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	CapIat        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=cap_iat,json=capIat,proto3" json:"cap_iat,omitempty"`
	CapExp        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=cap_exp,json=capExp,proto3" json:"cap_exp,omitempty"`
	OpenedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpen) Reset() {
	*x = SessionOpen{}
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpen) ProtoMessage() {}

func (x *SessionOpen) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpen.ProtoReflect.Descriptor instead.
func (*SessionOpen) Descriptor() ([]byte, []int) {
	return file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP(), []int{2}
}

func (x *SessionOpen) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SessionOpen) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionOpen) GetExeId() string {
	if x != nil {
		return x.ExeId
	}
	return ""
}

func (x *SessionOpen) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *SessionOpen) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SessionOpen) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionOpen) GetCapIat() *timestamppb.Timestamp {
	if x != nil {
		return x.CapIat
	}
	return nil
}

func (x *SessionOpen) GetCapExp() *timestamppb.Timestamp {
	if x != nil {
		return x.CapExp
	}
	return nil
}

func (x *SessionOpen) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

type SessionClose struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClosedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	CloseReason     string                 `protobuf:"bytes,3,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	FramesToBackend int32                  `protobuf:"varint,4,opt,name=frames_to_backend,json=framesToBackend,proto3" json:"frames_to_backend,omitempty"`
	FramesToClient  int32                  `protobuf:"varint,5,opt,name=frames_to_client,json=framesToClient,proto3" json:"frames_to_client,omitempty"`
	BytesToBackend  int64                  `protobuf:"varint,6,opt,name=bytes_to_backend,json=bytesToBackend,proto3" json:"bytes_to_backend,omitempty"`
	BytesToClient   int64                  `protobuf:"varint,7,opt,name=bytes_to_client,json=bytesToClient,proto3" json:"bytes_to_client,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP(), []int{3}
}

func (x *SessionClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionClose) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *SessionClose) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *SessionClose) GetFramesToBackend() int32 {
	if x != nil {
		return x.FramesToBackend
	}
	return 0
}

func (x *SessionClose) GetFramesToClient() int32 {
	if x != nil {
		return x.FramesToClient
	}
	return 0
}

func (x *SessionClose) GetBytesToBackend() int64 {
	if x != nil {
		return x.BytesToBackend
	}
	return 0
}

func (x *SessionClose) GetBytesToClient() int64 {
	if x != nil {
		return x.BytesToClient
	}
	return 0
}

type CallStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // empty for rest/relay
	WorkspaceId   string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExeId         string                 `protobuf:"bytes,5,opt,name=exe_id,json=exeId,proto3" json:"exe_id,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"` // "envmcp"|"rest"|"relay"
	RpcId         string                 `protobuf:"bytes,7,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	RpcMethod     string                 `protobuf:"bytes,8,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`
	RpcKind       string                 `protobuf:"bytes,9,opt,name=rpc_kind,json=rpcKind,proto3" json:"rpc_kind,omitempty"`
	RequestBytes  []byte                 `protobuf:"bytes,10,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"` // inline if size <= payload_max; empty if >
	RequestSize   int32                  `protobuf:"varint,11,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	RequestSha256 string                 `protobuf:"bytes,12,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStart) Reset() {
	*x = CallStart{}
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStart) ProtoMessage() {}

func (x *CallStart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_exec_audit_pb_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStart.ProtoReflect.Descriptor instead.
func (*CallStart) Descriptor() ([]byte, []int) {
	return file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP(), []int{4}
}

func (x *CallStart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallStart) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CallStart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CallStart) GetExeId() string {
	if x != nil {
		return x.ExeId
	}
	return ""
}

func (x *CallStart) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CallStart) GetRpcId() string {
	if x != nil {
		return x.RpcId
	}
	return ""
}

func (x *CallStart) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *CallStart) GetRpcKind() string {
	if x != nil {
		return x.RpcKind
	}
	return ""
}

func (x *CallStart) GetRequestBytes() []byte {
	if x != nil {
		return x.RequestBytes
	}
	return nil
}

func (x *CallStart) GetRequestSize() int32 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *CallStart) GetRequestSha256() string {
	if x != nil {
		return x.RequestSha256
	}
	return ""
}

func (x *CallStart) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

var File_internal_server_exec_audit_pb_audit_proto protoreflect.FileDescriptor

const file_internal_server_exec_audit_pb_audit_proto_rawDesc = "" +
	"\n" +
	")internal/server/exec_audit_pb/audit.proto\x12\texecaudit\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\fBatchRecords\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12.\n" +
	"\arecords\x18\x02 \x03(\v2\x14.execaudit.WALRecordR\arecords\"\xa2\x02\n" +
	"\tWALRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\fsession_open\x18\x02 \x01(\v2\x16.execaudit.SessionOpenH\x00R\vsessionOpen\x12>\n" +
	"\rsession_close\x18\x03 \x01(\v2\x17.execaudit.SessionCloseH\x00R\fsessionClose\x125\n" +
	"\n" +
	"call_start\x18\x04 \x01(\v2\x14.execaudit.CallStartH\x00R\tcallStart\x129\n" +
	"\n" +
	"written_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twrittenAtB\x06\n" +
	"\x04bodyJ\x04\b\x05\x10\x06R\bcall_end\"\xd6\x02\n" +
	"\vSessionOpen\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06exe_id\x18\x03 \x01(\tR\x05exeId\x12\x17\n" +
	"\aturn_id\x18\x04 \x01(\tR\x06turnId\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x123\n" +
	"\acap_iat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06capIat\x123\n" +
	"\acap_exp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06capExp\x127\n" +
	"\topened_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bopenedAt\"\xb1\x02\n" +
	"\fSessionClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\tclosed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12!\n" +
	"\fclose_reason\x18\x03 \x01(\tR\vcloseReason\x12*\n" +
	"\x11frames_to_backend\x18\x04 \x01(\x05R\x0fframesToBackend\x12(\n" +
	"\x10frames_to_client\x18\x05 \x01(\x05R\x0eframesToClient\x12(\n" +
	"\x10bytes_to_backend\x18\x06 \x01(\x03R\x0ebytesToBackend\x12&\n" +
	"\x0fbytes_to_client\x18\a \x01(\x03R\rbytesToClient\"\xa9\x03\n" +
	"\tCallStart\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x15\n" +
	"\x06exe_id\x18\x05 \x01(\tR\x05exeId\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x15\n" +
	"\x06rpc_id\x18\a \x01(\tR\x05rpcId\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\b \x01(\tR\trpcMethod\x12\x19\n" +
	"\brpc_kind\x18\t \x01(\tR\arpcKind\x12#\n" +
	"\rrequest_bytes\x18\n" +
	" \x01(\fR\frequestBytes\x12!\n" +
	"\frequest_size\x18\v \x01(\x05R\vrequestSize\x12%\n" +
	"\x0erequest_sha256\x18\f \x01(\tR\rrequestSha256\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAtBNZLgithub.com/agentserver/agentserver/internal/server/exec_audit_pb;execauditpbb\x06proto3"

var (
	file_internal_server_exec_audit_pb_audit_proto_rawDescOnce sync.Once
	file_internal_server_exec_audit_pb_audit_proto_rawDescData []byte
)

func file_internal_server_exec_audit_pb_audit_proto_rawDescGZIP() []byte {
	file_internal_server_exec_audit_pb_audit_proto_rawDescOnce.Do(func() {
		file_internal_server_exec_audit_pb_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_exec_audit_pb_audit_proto_rawDesc), len(file_internal_server_exec_audit_pb_audit_proto_rawDesc)))
	})
	return file_internal_server_exec_audit_pb_audit_proto_rawDescData
}

var file_internal_server_exec_audit_pb_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_server_exec_audit_pb_audit_proto_goTypes = []any{
	(*BatchRecords)(nil),          // 0: execaudit.BatchRecords
	(*WALRecord)(nil),             // 1: execaudit.WALRecord
	(*SessionOpen)(nil),           // 2: execaudit.SessionOpen
	(*SessionClose)(nil),          // 3: execaudit.SessionClose
	(*CallStart)(nil),             // 4: execaudit.CallStart
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_internal_server_exec_audit_pb_audit_proto_depIdxs = []int32{
	1,  // 0: execaudit.BatchRecords.records:type_name -> execaudit.WALRecord
	2,  // 1: execaudit.WALRecord.session_open:type_name -> execaudit.SessionOpen
	3,  // 2: execaudit.WALRecord.session_close:type_name -> execaudit.SessionClose
	4,  // 3: execaudit.WALRecord.call_start:type_name -> execaudit.CallStart
	5,  // 4: execaudit.WALRecord.written_at:type_name -> google.protobuf.Timestamp
	5,  // 5: execaudit.SessionOpen.cap_iat:type_name -> google.protobuf.Timestamp
	5,  // 6: execaudit.SessionOpen.cap_exp:type_name -> google.protobuf.Timestamp
	5,  // 7: execaudit.SessionOpen.opened_at:type_name -> google.protobuf.Timestamp
	5,  // 8: execaudit.SessionClose.closed_at:type_name -> google.protobuf.Timestamp
	5,  // 9: execaudit.CallStart.started_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_server_exec_audit_pb_audit_proto_init() }
func file_internal_server_exec_audit_pb_audit_proto_init() {
	if File_internal_server_exec_audit_pb_audit_proto != nil {
		return
	}
	file_internal_server_exec_audit_pb_audit_proto_msgTypes[1].OneofWrappers = []any{
		(*WALRecord_SessionOpen)(nil),
		(*WALRecord_SessionClose)(nil),
		(*WALRecord_CallStart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_exec_audit_pb_audit_proto_rawDesc), len(file_internal_server_exec_audit_pb_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_server_exec_audit_pb_audit_proto_goTypes,
		DependencyIndexes: file_internal_server_exec_audit_pb_audit_proto_depIdxs,
		MessageInfos:      file_internal_server_exec_audit_pb_audit_proto_msgTypes,
	}.Build()
	File_internal_server_exec_audit_pb_audit_proto = out.File
	file_internal_server_exec_audit_pb_audit_proto_goTypes = nil
	file_internal_server_exec_audit_pb_audit_proto_depIdxs = nil
}
