// Package devfixtures implements the explicitly insecure, loopback-only
// external dependencies used by the agentserver v2 development stack. It is
// deterministic test infrastructure, not a Hydra or llmproxy replacement.
package devfixtures

import (
	"bytes"
	"crypto/subtle"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/agentserver/agentserver/v2/internal/braincatalog"
	"github.com/agentserver/agentserver/v2/internal/runcapability"
)

const (
	CurrentConfigVersion = 2

	RelativeConfigPath             = "config/dev-fixtures.json"
	RelativeBrowserBearerTokenPath = "secrets/browser-bearer.token"
	RelativeRunCapabilityKeyPath   = "secrets/run-capability.key"
	RelativeExternalOIDCSecretPath = "secrets/external-oidc-client.secret"
	RelativeLLMProxyCertificate    = "pki/llmproxy.crt"
	RelativeLLMProxyPrivateKey     = "pki/llmproxy.key"

	BrowserTokenAudience   = "agentserver-api"
	BrowserTokenScope      = "runs:write"
	BrowserOAuthClientID   = "agentserver-web"
	ExternalOIDCClientID   = "agentserver-core"
	ExternalOIDCSubject    = "agentserver-dev-user"
	ToolNamespace          = "executor"
	ScriptedToolName       = "list_environments"
	ScriptedShellName      = "shell"
	CancellationHoldMarker = "[agentserver-dev-cancel-hold]"
	ApprovalDenyMarker     = "[agentserver-dev-approval-deny]"
	ApprovalExpiryMarker   = "[agentserver-dev-approval-expiry]"
	ApprovalCancelMarker   = "[agentserver-dev-approval-cancel]"
	ApprovalFailureMessage = "Agentserver v2 scripted approval failure was contained."

	maximumConfigBytes = int64(128 * 1024)
	maximumSecretBytes = int64(32 * 1024)
	llmproxySPIFFEID   = "spiffe://agentserver.dev/ns/insecure-dev/sa/llmproxy"
)

var uuidPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// ConfigDocument is generated by agentserver-dev prepare. Secret values are
// intentionally represented only by absolute paths inside the prepared
// bundle.
type ConfigDocument struct {
	Version   int               `json:"version"`
	Authority AuthorityDocument `json:"authority"`
	Hydra     HydraDocument     `json:"hydra"`
	LLMProxy  LLMProxyDocument  `json:"llmproxy"`
}

type AuthorityDocument struct {
	WorkspaceID string `json:"workspaceId"`
	SessionID   string `json:"sessionId"`
	ActorID     string `json:"actorId"`
}

type HydraDocument struct {
	IntrospectionEndpoint  string               `json:"introspectionEndpoint"`
	BrowserBearerTokenFile string               `json:"browserBearerTokenFile"`
	Audience               string               `json:"audience"`
	Scope                  string               `json:"scope"`
	ResponseTTL            string               `json:"responseTtl"`
	PublicOrigin           string               `json:"publicOrigin"`
	BrowserClientID        string               `json:"browserClientId"`
	BrowserRedirectURI     string               `json:"browserRedirectUri"`
	LoginURL               string               `json:"loginUrl"`
	ConsentURL             string               `json:"consentUrl"`
	ExternalOIDC           ExternalOIDCDocument `json:"externalOidc"`
}

type ExternalOIDCDocument struct {
	Issuer           string `json:"issuer"`
	AuthorizationURL string `json:"authorizationUrl"`
	ClientID         string `json:"clientId"`
	ClientSecretFile string `json:"clientSecretFile"`
	RedirectURI      string `json:"redirectUri"`
	Subject          string `json:"subject"`
}

type LLMProxyDocument struct {
	Endpoint             string `json:"endpoint"`
	CertificateFile      string `json:"certificateFile"`
	PrivateKeyFile       string `json:"privateKeyFile"`
	RunCapabilityKeyFile string `json:"runCapabilityKeyFile"`
	Model                string `json:"model"`
	Provider             string `json:"provider"`
	ToolNamespace        string `json:"toolNamespace"`
	ScriptedTool         string `json:"scriptedTool"`
	FinalMessage         string `json:"finalMessage"`
}

// Bundle is a fully loaded fixture configuration. It owns in-memory copies of
// the browser bearer and capability verifier; neither is exposed by metadata.
type Bundle struct {
	document                 ConfigDocument
	hydraEndpoint            *url.URL
	llmEndpoint              *url.URL
	hydraListen              string
	llmListen                string
	responseTTL              time.Duration
	browserToken             []byte
	externalOIDCClientSecret []byte
	codec                    *runcapability.DevelopmentCodec
	tlsIdentity              tls.Certificate
}

func LoadBundle(bundleDirectory string) (*Bundle, error) {
	if err := validateBundleDirectory(bundleDirectory); err != nil {
		return nil, err
	}
	configPath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeConfigPath))
	raw, err := readRestrictedFile("development fixture config", configPath, maximumConfigBytes)
	if err != nil {
		return nil, err
	}
	limits := braincatalog.DefaultLimits()
	limits.MaxJSONValues = 512
	limits.MaxJSONDepth = 8
	if _, _, err := braincatalog.DecodeCanonicalJSON(raw, int(maximumConfigBytes), limits); err != nil {
		return nil, fmt.Errorf("validate development fixture config JSON: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	var document ConfigDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("decode development fixture config: %w", err)
	}
	if err := finishJSON(decoder); err != nil {
		return nil, fmt.Errorf("finish development fixture config: %w", err)
	}

	hydraEndpoint, hydraListen, llmEndpoint, llmListen, responseTTL, err := validateDocument(document, bundleDirectory)
	if err != nil {
		return nil, err
	}
	browserTokenPath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeBrowserBearerTokenPath))
	browserTokenRaw, err := readRestrictedFile("development browser bearer", browserTokenPath, maximumSecretBytes)
	if err != nil {
		return nil, err
	}
	browserToken, err := parseBrowserToken(browserTokenRaw)
	clear(browserTokenRaw)
	if err != nil {
		return nil, err
	}
	externalSecretPath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeExternalOIDCSecretPath))
	externalSecretRaw, err := readRestrictedFile("development external OIDC client secret", externalSecretPath, maximumSecretBytes)
	if err != nil {
		clear(browserToken)
		return nil, err
	}
	externalSecretLine, err := parseSecretLine("development external OIDC client secret", externalSecretRaw)
	clear(externalSecretRaw)
	if err != nil || len(externalSecretLine) < 43 || len(externalSecretLine) > 128 {
		clear(browserToken)
		return nil, errors.New("development external OIDC client secret is invalid")
	}
	externalSecret := []byte(externalSecretLine)

	capabilityKeyPath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeRunCapabilityKeyPath))
	capabilityKeyRaw, err := readRestrictedFile("development run capability key", capabilityKeyPath, maximumSecretBytes)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, err
	}
	encodedKey, err := parseSecretLine("development run capability key", capabilityKeyRaw)
	clear(capabilityKeyRaw)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, err
	}
	codec, err := runcapability.NewDevelopmentCodecFromBase64Key(encodedKey)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, fmt.Errorf("load development run capability key: %w", err)
	}

	certificatePath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeLLMProxyCertificate))
	privateKeyPath := filepath.Join(bundleDirectory, filepath.FromSlash(RelativeLLMProxyPrivateKey))
	certificateRaw, err := readRestrictedFile("development llmproxy certificate", certificatePath, maximumSecretBytes)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, err
	}
	clear(certificateRaw)
	privateKeyRaw, err := readRestrictedFile("development llmproxy private key", privateKeyPath, maximumSecretBytes)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, err
	}
	clear(privateKeyRaw)
	identity, err := tls.LoadX509KeyPair(certificatePath, privateKeyPath)
	if err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, fmt.Errorf("load development llmproxy TLS identity: %w", err)
	}
	if err := validateLLMProxyIdentity(&identity, llmEndpoint.Hostname()); err != nil {
		clear(browserToken)
		clear(externalSecret)
		return nil, err
	}

	return &Bundle{
		document: document, hydraEndpoint: hydraEndpoint, llmEndpoint: llmEndpoint,
		hydraListen: hydraListen, llmListen: llmListen, responseTTL: responseTTL,
		browserToken: browserToken, externalOIDCClientSecret: externalSecret,
		codec: codec, tlsIdentity: identity,
	}, nil
}

func validateDocument(document ConfigDocument, bundleDirectory string) (*url.URL, string, *url.URL, string, time.Duration, error) {
	if document.Version != CurrentConfigVersion {
		return nil, "", nil, "", 0, fmt.Errorf("development fixture config version must be %d", CurrentConfigVersion)
	}
	for name, value := range map[string]string{
		"authority.workspaceId": document.Authority.WorkspaceID,
		"authority.sessionId":   document.Authority.SessionID,
		"authority.actorId":     document.Authority.ActorID,
	} {
		if value == "00000000-0000-0000-0000-000000000000" || !uuidPattern.MatchString(value) {
			return nil, "", nil, "", 0, fmt.Errorf("development fixture %s must be a non-zero canonical lowercase UUID", name)
		}
	}
	hydraEndpoint, hydraListen, err := validateEndpoint("hydra.introspectionEndpoint", document.Hydra.IntrospectionEndpoint, "http")
	if err != nil {
		return nil, "", nil, "", 0, err
	}
	llmEndpoint, llmListen, err := validateEndpoint("llmproxy.endpoint", document.LLMProxy.Endpoint, "https")
	if err != nil {
		return nil, "", nil, "", 0, err
	}
	if hydraListen == llmListen {
		return nil, "", nil, "", 0, errors.New("development Hydra and llmproxy fixtures must use distinct loopback listeners")
	}
	if document.Hydra.BrowserBearerTokenFile != filepath.Join(bundleDirectory, filepath.FromSlash(RelativeBrowserBearerTokenPath)) {
		return nil, "", nil, "", 0, errors.New("development Hydra fixture bearer path is not the exact prepared-bundle path")
	}
	if document.Hydra.Audience != BrowserTokenAudience || document.Hydra.Scope != BrowserTokenScope {
		return nil, "", nil, "", 0, errors.New("development Hydra fixture audience or scope is unsupported")
	}
	fixtureOrigin := hydraEndpoint.Scheme + "://" + hydraEndpoint.Host
	if document.Hydra.PublicOrigin == "" || document.Hydra.BrowserClientID != BrowserOAuthClientID ||
		document.Hydra.BrowserRedirectURI != document.Hydra.PublicOrigin+"/" ||
		document.Hydra.LoginURL != document.Hydra.PublicOrigin+"/auth/hydra/login" ||
		document.Hydra.ConsentURL != document.Hydra.PublicOrigin+"/auth/hydra/consent" {
		return nil, "", nil, "", 0, errors.New("development Hydra public client or bridge URLs are unsupported")
	}
	publicOrigin, err := url.Parse(document.Hydra.PublicOrigin)
	if err != nil || publicOrigin.Scheme != "https" || publicOrigin.User != nil || publicOrigin.RawQuery != "" || publicOrigin.Fragment != "" ||
		(publicOrigin.Path != "" && publicOrigin.Path != "/") {
		return nil, "", nil, "", 0, errors.New("development Hydra public origin must be an exact HTTPS origin")
	}
	if document.Hydra.ExternalOIDC.Issuer != fixtureOrigin+"/idp" ||
		document.Hydra.ExternalOIDC.AuthorizationURL != document.Hydra.PublicOrigin+"/auth/idp/authorize" ||
		document.Hydra.ExternalOIDC.ClientID != ExternalOIDCClientID ||
		document.Hydra.ExternalOIDC.ClientSecretFile != filepath.Join(bundleDirectory, filepath.FromSlash(RelativeExternalOIDCSecretPath)) ||
		document.Hydra.ExternalOIDC.RedirectURI != document.Hydra.PublicOrigin+"/auth/oidc/callback" ||
		document.Hydra.ExternalOIDC.Subject != ExternalOIDCSubject {
		return nil, "", nil, "", 0, errors.New("development external OIDC fixture authority is unsupported")
	}
	responseTTL, err := time.ParseDuration(document.Hydra.ResponseTTL)
	if err != nil || responseTTL < time.Minute || responseTTL > 24*time.Hour {
		return nil, "", nil, "", 0, errors.New("development Hydra response TTL must be a Go duration between 1m and 24h")
	}
	for _, file := range []struct {
		name     string
		actual   string
		relative string
	}{
		{"llmproxy.certificateFile", document.LLMProxy.CertificateFile, RelativeLLMProxyCertificate},
		{"llmproxy.privateKeyFile", document.LLMProxy.PrivateKeyFile, RelativeLLMProxyPrivateKey},
		{"llmproxy.runCapabilityKeyFile", document.LLMProxy.RunCapabilityKeyFile, RelativeRunCapabilityKeyPath},
	} {
		if file.actual != filepath.Join(bundleDirectory, filepath.FromSlash(file.relative)) {
			return nil, "", nil, "", 0, fmt.Errorf("development fixture %s is not the exact prepared-bundle path", file.name)
		}
	}
	for name, value := range map[string]string{
		"llmproxy.model": document.LLMProxy.Model, "llmproxy.provider": document.LLMProxy.Provider,
		"llmproxy.finalMessage": document.LLMProxy.FinalMessage,
	} {
		maximum := 256
		if name == "llmproxy.finalMessage" {
			maximum = 4096
		}
		if !canonicalText(value, maximum) {
			return nil, "", nil, "", 0, fmt.Errorf("development fixture %s is invalid", name)
		}
	}
	if document.LLMProxy.ToolNamespace != ToolNamespace || document.LLMProxy.ScriptedTool != ScriptedToolName {
		return nil, "", nil, "", 0, errors.New("development llmproxy fixture must start its deterministic script with executor.list_environments")
	}
	return hydraEndpoint, hydraListen, llmEndpoint, llmListen, responseTTL, nil
}

func validateEndpoint(name, raw, scheme string) (*url.URL, string, error) {
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme != scheme || parsed.Opaque != "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" ||
		parsed.RawPath != "" || parsed.ForceQuery || parsed.Path == "" || parsed.Path == "/" || strings.HasSuffix(parsed.Path, "/") {
		return nil, "", fmt.Errorf("development fixture %s must be an exact %s loopback endpoint", name, scheme)
	}
	host, portText, err := net.SplitHostPort(parsed.Host)
	if err != nil || host == "" {
		return nil, "", fmt.Errorf("development fixture %s must contain an explicit loopback host and port", name)
	}
	port, err := strconv.ParseUint(portText, 10, 16)
	if err != nil || port == 0 || strconv.FormatUint(port, 10) != portText || net.JoinHostPort(host, portText) != parsed.Host {
		return nil, "", fmt.Errorf("development fixture %s must contain a canonical non-zero port", name)
	}
	if !canonicalLoopbackHost(host) {
		return nil, "", fmt.Errorf("development fixture %s must use a canonical explicit loopback host", name)
	}
	if strings.Contains(parsed.Path, "%") || parsed.String() != raw {
		return nil, "", fmt.Errorf("development fixture %s must use canonical URL spelling", name)
	}
	return parsed, parsed.Host, nil
}

func canonicalLoopbackHost(host string) bool {
	if host == "localhost" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback() && ip.String() == host
}

func validateBundleDirectory(path string) error {
	if path == "" || !filepath.IsAbs(path) || filepath.Clean(path) != path || strings.ContainsRune(path, 0) {
		return errors.New("development fixture bundle must be an absolute clean path")
	}
	info, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("inspect development fixture bundle: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0o077 != 0 {
		return errors.New("development fixture bundle must be a direct private directory")
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil || resolved != path {
		return errors.New("development fixture bundle must have no symlinked path components")
	}
	return nil
}

func readRestrictedFile(name, path string, maximum int64) ([]byte, error) {
	if path == "" || !filepath.IsAbs(path) || filepath.Clean(path) != path || strings.ContainsRune(path, 0) {
		return nil, fmt.Errorf("%s path must be absolute and canonical", name)
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil || resolved != path {
		return nil, fmt.Errorf("%s path must have no symlinked components", name)
	}
	info, err := os.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("inspect %s: %w", name, err)
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0o077 != 0 || info.Size() < 1 || info.Size() > maximum {
		return nil, fmt.Errorf("%s must be a direct, private, non-empty regular file no larger than %d bytes", name, maximum)
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", name, err)
	}
	raw, readErr := io.ReadAll(io.LimitReader(file, maximum+1))
	after, statErr := file.Stat()
	closeErr := file.Close()
	if readErr != nil || statErr != nil || closeErr != nil {
		return nil, errors.Join(readErr, statErr, closeErr)
	}
	if int64(len(raw)) != info.Size() || int64(len(raw)) > maximum || !os.SameFile(info, after) || after.Size() != info.Size() {
		clear(raw)
		return nil, fmt.Errorf("%s identity or size changed while reading", name)
	}
	return raw, nil
}

func parseBrowserToken(raw []byte) ([]byte, error) {
	line, err := parseSecretLine("development browser bearer", raw)
	if err != nil {
		return nil, err
	}
	const prefix = "asv2dev-browser-"
	encoded, ok := strings.CutPrefix(line, prefix)
	if !ok {
		return nil, errors.New("development browser bearer has an invalid prefix")
	}
	decoded, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil || len(decoded) != 32 || base64.RawURLEncoding.EncodeToString(decoded) != encoded {
		clear(decoded)
		return nil, errors.New("development browser bearer must contain canonical 256-bit base64url entropy")
	}
	clear(decoded)
	return []byte(line), nil
}

func parseSecretLine(name string, raw []byte) (string, error) {
	if len(raw) < 2 || raw[len(raw)-1] != '\n' || bytes.Contains(raw[:len(raw)-1], []byte{'\n'}) || bytes.ContainsRune(raw, '\r') {
		return "", fmt.Errorf("%s must contain exactly one newline-terminated line", name)
	}
	line := raw[:len(raw)-1]
	if !utf8.Valid(line) || len(bytes.TrimSpace(line)) != len(line) || bytes.ContainsRune(line, 0) {
		return "", fmt.Errorf("%s contains invalid text", name)
	}
	return string(line), nil
}

func validateLLMProxyIdentity(identity *tls.Certificate, hostname string) error {
	if identity == nil || len(identity.Certificate) != 1 {
		return errors.New("development llmproxy TLS identity must contain exactly one leaf certificate")
	}
	leaf, err := x509.ParseCertificate(identity.Certificate[0])
	if err != nil {
		return fmt.Errorf("parse development llmproxy leaf certificate: %w", err)
	}
	if err := leaf.VerifyHostname(hostname); err != nil {
		return fmt.Errorf("development llmproxy certificate does not cover configured endpoint: %w", err)
	}
	if len(leaf.URIs) != 1 || leaf.URIs[0].String() != llmproxySPIFFEID {
		return errors.New("development llmproxy certificate has the wrong SPIFFE identity")
	}
	identity.Leaf = leaf
	return nil
}

func canonicalText(value string, maximum int) bool {
	return value != "" && len(value) <= maximum && utf8.ValidString(value) && strings.TrimSpace(value) == value && !strings.ContainsAny(value, "\x00\r\n")
}

func finishJSON(decoder *json.Decoder) error {
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("document contains more than one JSON value")
		}
		return err
	}
	return nil
}

func exactTokenEqual(left []byte, right string) bool {
	if len(left) != len(right) {
		return false
	}
	return subtle.ConstantTimeCompare(left, []byte(right)) == 1
}
